/**
 * Reads package.json version and writes src/core/version.ts.
 * Run via: bun run gen:version
 * Wired into the build script so dist always reflects the real version.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")) as {
  version?: unknown;
};

const version =
  typeof pkg.version === "string" && pkg.version.length > 0
    ? pkg.version
    : "0.0.0-dev";

const content = `/**
 * Build-time-injected package version.
 * Generated by \`scripts/gen-version.ts\` — do not edit by hand.
 * Re-generate with: bun run gen:version
 */
export const SKAWLD_VERSION = "${version}";
`;

const outPath = resolve(root, "src/core/version.ts");
writeFileSync(outPath, content, "utf8");
console.log(`gen:version → ${version}`);
